taskbox/config/routes.rb
Rails.application.routes.draw do

  resources :announcements
  
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :catgories

  devise_for :users
  root to: "clients#index"

  resources :clients
  resources :projects
  resources :tasks

  get 'sandbox/clients'
  get 'sandbox/projects'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/products'

  get 'tasker/task'

end

taskbox/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == "admin"
        can [:read], :manage,:all 
    elsif user.role == "user"
        can :manage, [Client, Project, Task]
    end
            
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

taskbox/app/models/announcement.rb
class Announcement < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :title, :content
	validates_length_of :content, minimum: 10
end

taskbox/app/models/catgory.rb
class Catgory < ActiveRecord::Base
	belongs_to :user

	has_many :project_catgories
	has_many :projects, through: :project_catgories

	validates_presence_of :name
end

taskbox/app/models/client.rb
class Client < ActiveRecord::Base

	has_many :projects
	belongs_to :user

	before_create :generate_code
	before_destroy :destroy_projects

	#Validations
	validates_presence_of :name, :company, :email, :mobile_number
	validates_length_of :mobile_number, is: 10
	validates_numericality_of :mobile_number
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates_uniqueness_of :mobile_number, :email, scope: :user_id

	def list_projects
		Project.where('client_id = ?', self.id)
	end

	def list_by_status(status)
		Project.where('client_id = ? AND status = ?', self.id, status)
	end

	def details
		"NAME: #{self.name} <br>" +
		"COMPANY: #{self.company} <br>" +
		"EMAIL: #{self.email} <br>" +
		"MOBILE: #{self.mobile_number}"
	end

	def generate_code
		self.code = "#{self.name[0..3].upcase}#{Random.rand(10000)}"
	end

	def destroy_projects
		self.projects.each do |project|
			project.destroy
		end
	end
end

taskbox/app/models/project.rb
class Project < ActiveRecord::Base

	belongs_to :client
	belongs_to :project
	has_many :tasks

	has_many :project_catgories
	has_many :catgories, through: :project_catgories

	before_destroy :destroy_tasks

	validates_presence_of :name, :description, :start_date, :end_date, :estimated_budget, :status
	validates_length_of :description, minimum: 10

	validate :check_date

	def self.new_projects
		Project.where('status = ?', 'New')
	end

	def self.all_projects
		Project.all
	end

	def list_tasks
		Task.where('project_id = ?', self.id)
	end

	def details
		"<h3>NAME</h3> #{self.name} <br/>" + 
		"<h3>CLIENT</h3> <%= link_to #{Client.find(self.client_id).name}, client_path(project.client_id) %> <br/>" + 
		"<h3>DESCRIPTION</h3> #{self.description} <br/>" + 
		"<h3>START DATE</h3> #{self.start_date.strftime("%A, %d %B %Y")} <br/>" +
		"<h3>END DATE</h3>#{self.end_date.strftime("%A, %d %B %Y")}<br/>"
	end

	def destroy_tasks
		self.tasks.each do |task|
			task.destroy
		end
	end

	private 
	def check_date
		if self.end_date <= self.start_date
			errors.add(:end_date, "should be greater than Start Date")
		end
	end
end

taskbox/app/models/project_catgory.rb
class ProjectCatgory < ActiveRecord::Base
	belongs_to :project
	belongs_to :catgory
end

taskbox/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project

	validates_presence_of :title, :due_date
	#validates_numericality_of :project_id

	#validate :check_due_date

	def self.list_by_complete
		Task.where('is_completed = ?', true)
	end

	def self.list_by_incomplete
		Task.where('is_completed = ?', false)
	end

	def self.list_by_overdue
		Task.where('due_date < ?', Date.today)
	end

	private

	def check_due_date
		if (!self.due_date.nil?) && (self.due_date > project.end_date || self.due_date < project.start_date)
			errors.add(:due_date, "should be between #{project.start_date} and #{project.end_date}")
		end
	end
end

taskbox/app/models/user.rb
class User < ActiveRecord::Base
	has_many :clients
	has_many :projects
	has_many :catgories
	has_many :announcements
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def is_admin?
         	return true if self.role == "admin"
         end
end

taskbox/app/controllers/say_controller.rb
class SayController < ApplicationController

  authorize_resource class: false
  def hello
  end

  def goodbye
  end

  def products
  	@products = {		"Surface Pro" => ["Microsoft", 12.3, 128, "Windows 10", 849.99], 
						"Galaxy Tab S2" => ["Samsung", 8, 32, "Android 6 Marshmello", 299.99], 
						"Fire" => ["Amazon", 7, 8, "Android Open Source: Amazon", 49.99],
						"iPad Air 2" => ["Apple", 9.7, 64, "iOS 8.1", 499.99]	}
  end
end

taskbox/app/controllers/tasker_controller.rb
class TaskerController < ApplicationController
	def tasks
		@tasks = Tasks.all
	end
end

taskbox/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_filter :authenticate_user!
	load_and_authorize_resource
	
	def index
		@tasks = Task.all
	end

	def create
		@task = Task.new(task_params)
		if @task.save
			redirect_to project_path(@task.project_id), notice: "Successfully created the task!"
		end
	end

	def show
		@task = Task.find(params[:id])
	end

	def mark_as_complete
		task = Task.find(params[:task_id])
		task.update_attributes(is_completed: true)
		Notification.completed(task, current_user).deliver!
		redirect_to :back, notice: "Successfully marked task as complete."
	end

	def mark_as_incomplete
		task = Task.find(params[:task_id])
		task.update_attributes(is_completed: false)
		Notification.incomplete(task, current_user).deliver!
		redirect_to :back, notice: "Successfully marked task as incomplete."
	end

	private
	def task_params
		params[:task].permit(:title, :due_date, :is_completed, :project_id)
	end
end

taskbox/app/helpers/annoucements_helper.rb
module AnnoucementsHelper
end

taskbox/app/helpers/application_helper.rb
module ApplicationHelper
end

taskbox/app/helpers/catgories_helper.rb
module CatgoriesHelper
end

taskbox/app/helpers/clients_helper.rb
module ClientsHelper
end

taskbox/app/helpers/projects_helper.rb
module ProjectsHelper
end

taskbox/app/helpers/sandbox_helper.rb
module SandboxHelper
end

taskbox/app/helpers/say_helper.rb
module SayHelper
end

taskbox/app/helpers/tasker_helper.rb
module TaskerHelper
end

taskbox/app/helpers/tasks_helper.rb
module TasksHelper
end

taskbox/app/views/announcement_notification/notify.html.erb
<p>Sent to: <%= @clients%>,</p>
<p>Hi,</p>
<p><%= @announcement.content %></p>

<p>Regards,<br/>Team Taskbox</p>

taskbox/app/views/announcement_notification/notify.text.erb
AnnouncementNotification#notify

<%= @greeting %>, find me in app/views/announcement_notification/notify.text.erb

taskbox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">

  <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<h1 class="bg-info"><br/><em>Taskbox Application</em></h1>

<% if user_signed_in? #Checks whether the user is logged in.%>

	<nav class="navbar navbar-default">
  		<div class="container-fluid">
   		 <!-- Brand and toggle get grouped for better mobile display -->
   		<div class="navbar-header">
      		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        	<span class="sr-only">Toggle navigation</span>
        	<span class="icon-bar"></span>
        	<span class="icon-bar"></span>
        	<span class="icon-bar"></span>
      		</button>
      		<a class="navbar-brand" href="/">Home</a>
    	</div>

    	<!-- Collect the nav links, forms, and other content for toggling -->
    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      		<ul class="nav navbar-nav">
            <li><%= link_to "List Projects", projects_path %></li>
        		<li><%= link_to "List Announcements", announcements_path %></li>
        		<li class="dropdown">
         		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clients

            <% if current_user.is_admin? %>
             <span class="badge"><%= Client.all.size %></span>
             <% else %>
             <span class="badge"><%= current_user.clients.size %></span>
             <% end %>  <span class="caret"></span> </a>
          		<ul class="dropdown-menu">
                <% if current_user.is_admin? %>
                  <% for client in Client.all %>
                    <% tasks = Task.joins(:project).where('projects.client_id = ?', client.id) %>
                    <li><%= link_to client_path(client) do %><%= client.name %> <span class="badge"><%= tasks.where('is_completed = ?', false).size %></span><% end %></li>
                  <% end %>
          			
                <% else %>
                  <% for client in current_user.clients %>
                    <% tasks = Task.joins(:project).where('projects.client_id = ?', client.id) %>
                    <li><%= link_to client_path(client) do %><%= client.name %> <span class="badge"><%= tasks.where(' is_completed = ?', false).size %></span><% end %></li>
                  <% end %>
                  <% end %>

          		</ul>
        		</li>
     		</ul>
      		<form class="navbar-form navbar-left">
        		<div class="form-group">
          			<input type="text" class="form-control" placeholder="Search">
        		</div>
        		<button type="submit" class="btn btn-default">Submit</button>
      		</form>
      		<ul class="nav navbar-nav navbar-right">
      			<li class="dropdown">
        	  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category Options<span class="caret"></span></a>
          		<ul class="dropdown-menu">
            		<li><%= link_to "List Categories", catgories_path%></li>
            		<li><%= link_to "Add Category", new_catgory_path%> </li>
          		</ul>
        		</li>

        		<li class="dropdown">
        	  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
          		<ul class="dropdown-menu">
            		<li><%= link_to "Account Settings", edit_user_registration_path%></li>
            		<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          		</ul>
        		</li>
      		</ul>
    	</div><!-- /.navbar-collapse -->
  	</div><!-- /.container-fluid -->
</nav>

<% if notice %>
	<div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

<% else %>
	<div class="btn-group" role="group" aria-label="...">
		<%= link_to "Sign in", new_user_session_path, class: "btn btn-success" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-warning" %>
	</div>
<% end %>

<p class="alert"><%= alert %></p>

<%= yield %>
</div>

</body>
</html>

taskbox/app/views/notification/completed.html.erb
<p>Hi <%= @task.project.client.name%>,</p>
<p>The task <%= @task.title %> belonging to <%= @task.project.name %> has been completed and closed. It was due on <%= @task.due_date.strftime("%A, %d %B %Y")%>.</p>

<p>Regards,<br/>Team Taskbox</p>

<%= image_tag("http://department.sunysuffolk.edu/DeptImages/StayonLongIslandScholarships_Images/SBU-wSUNY-horz_2clr_cmyk1_350w.jpg") %>

taskbox/app/views/notification/completed.text.erb
Notification#completed

<%= @greeting %>, find me in app/views/notification/completed.text.erb

taskbox/app/views/notification/incomplete.html.erb
<p>Hi <%= @task.project.client.name%>,</p>
<p>The task <%= @task.title %> belonging to <%= @task.project.name %> has been reopened. It is due on <%= @task.due_date.strftime("%A, %d %B %Y")%>.</p>

<p>Regards,<br/>Team Taskbox</p>

<%= image_tag("http://department.sunysuffolk.edu/DeptImages/StayonLongIslandScholarships_Images/SBU-wSUNY-horz_2clr_cmyk1_350w.jpg") %>

taskbox/app/views/notification/incomplete.text.erb
Notification#incomplete

<%= @greeting %>, find me in app/views/notification/incomplete.text.erb