taskbox/config/routes.rb
Rails.application.routes.draw do

  resources :announcements
  
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :catgories

  devise_for :users
  root to: "clients#index"

  resources :clients
  resources :projects
  resources :tasks

  get 'sandbox/clients'
  get 'sandbox/projects'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/products'

  get 'tasker/task'

end

taskbox/app/models/client.rb
class Client < ActiveRecord::Base

	has_many :projects
	belongs_to :user

	before_create :generate_code
	before_destroy :destroy_projects

	#Validations
	validates_presence_of :name, :company, :email, :mobile_number
	validates_length_of :mobile_number, is: 10
	validates_numericality_of :mobile_number
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates_uniqueness_of :mobile_number, :email, scope: :user_id

	def list_projects
		Project.where('client_id = ?', self.id)
	end

	def list_by_status(status)
		Project.where('client_id = ? AND status = ?', self.id, status)
	end

	def details
		"NAME: #{self.name} <br>" +
		"COMPANY: #{self.company} <br>" +
		"EMAIL: #{self.email} <br>" +
		"MOBILE: #{self.mobile_number}"
	end

	def generate_code
		self.code = "#{self.name[0..3].upcase}#{Random.rand(10000)}"
	end

	def destroy_projects
		self.projects.each do |project|
			project.destroy
		end
	end
end

taskbox/app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	before_filter :authenticate_user!
	load_and_authorize_resource

	def index
		if current_user.is_admin?
			@clients = Client.all
		else
			@clients = current_user.clients
		end
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		@client.user_id = current_user.id
		if @client.save
			redirect_to clients_path
		else
			render action: "new"
		end
	end

	def show
		begin
			@client = current_user.clients.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to clients_path, notice: "Client Not Found!"
		end
	end

	def edit
		@client = current_user.clients.find(params[:id])
	end

	def update
		@client = current_user.clients.find(params[:id])
		@client.user_id = current_user.id
		if @client.update_attributes(client_params)
			redirect_to client_path(@client.id), notice: "Successfully Updated!"
		else
			render action: "edit"
		end
	end

	def destroy
		@client = current_user.clients.find(params[:id])
		@client.destroy
		redirect_to clients_path, notice: "Successfully destroyed #{@client.name}'s records."
	end

	private
	def client_params
		#This paramter hash is available in the object params.
		params[:client].permit(:name, :company, :mobile_number, :email)
	end
end

taskbox/app/helpers/clients_helper.rb
module ClientsHelper
end

taskbox/app/views/clients/_form.html.erb
<%= form_for @client do |f| %>

	<% if @client.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<h4>These errors prohibit the form from being saved:</h4>
			<ul>
				<% for msg in @client.errors.full_messages %>
					<li><%= msg%></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<label>Name</label><br/>
		<%= f.text_field :name, class: "form-control", required: true %>
	</div>

	<div class="form-group">
		<label>Company</label><br/>
		<%= f.text_field :company, class: "form-control", required: true %>
	</div>

	<div class="form-group">
		<label>Mobile Number</label><br/>
		<%= f.text_field :mobile_number, class: "form-control", required: true %>
	</div>

	<div class="form-group">
		<label>Email</label><br/>
		<%= f.email_field :email, class: "form-control", required: true %>
	</div>

	<%= f.submit "Submit", class: "bt btn-success"%>
<% end %>

taskbox/app/views/clients/edit.html.erb
<h1>EDIT CLIENT</h1>
<%= render 'form' %>

taskbox/app/views/clients/index.html.erb
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
			<h1>Listing Clients</h1>
		</div>


		<%= link_to new_client_path, class: "btn btn-primary" do %>
		<span class="glyphicon glyphicon-plus"></span> New Client
		<% end %>

		<% if @clients.empty? %>
			<h3>NO CLIENTS FOUND!!</h3>

		<% else %>
			<h3><%= @clients.size%> CLIENTS FOUND</h3>

			<%= link_to clients_path(format: "xls"), class: "btn btn-info btn-sm pull-right" do %>
			<span class="glyphicon glyphicon-download-alt"></span>Export to Excel
			<% end %>

			<script>
				$(document).ready(function(){
    				$("#clients_table").DataTable();
				});
			</script>

			<table class="table table-striped" id="clients_table">
			<thead>
				<tr>
					<th>NAME</th>
					<th>COMPANY</th>
					<th>MOBILE NUMBER</th>
					<th>EMAIL</th>
					<th>NUMBER OF PROJECTS</th>
					<% if current_user.is_admin? %>
						<th>USER EMAIL</th>
					<% end %>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @clients.each_with_index do |client, index|%>
				<tr>
					<td><%= link_to "#{client.name}", client_path(client) %></td>
					<td><%= client.company %></td>
					<td><%= client.mobile_number %></td>
					<td><%= client.email %></td>
					<td><%= client.projects.size%></td>
					<% if current_user.is_admin? %>
						<td><%= client.user.email %></td>
					<% end %>
					<td>
					<div class="btn-group btn-group-sm" role="group" aria-label="...">
						<%= link_to client_path(client), class: "btn btn-info" do %>
						<span class="glyphicon glyphicon-eye-open"></span> Show<% end %>
						<%= link_to edit_client_path(client.id), class: "btn btn-warning" do %>
						<span class="glyphicon glyphicon-pencil"></span> Edit<% end %>
						<%= link_to client_path(client.id), data: {method: :delete, confirm: "Do you want to delete?"}, class: "btn btn-danger" do %>
						<span class="glyphicon glyphicon-trash"></span> Delete<% end %>
					</div>
					</td>
				</tr>
			<%end%>
		</tbody>
		</table>
	<% end %>
	<br/>
	<hr/>

	</div>
	<div class="col-md-4">
		<div class="page-header">
			<h1>Clients' Statistics</h1>
			<% if current_user.is_admin? %>
				<% 	data = {}
					for client in @clients
						projects_count = client.projects.size
						data[client.name] = projects_count
					end %>
			<% else %>
				<% 	data = {}
					for client in current_user.clients
						projects_count = client.projects.size
						data[client.name] = projects_count
					end %>
			<% end %>
			<%= pie_chart(data) %>
			<%= bar_chart(data) %>
		</div>
	</div>
</div>

taskbox/app/views/clients/index.xls.erb
<table border="2">
	<thead>
		<tr>
			<th>#</th>
			<th>NAME</th>
			<th>COMPANY</th>
			<th>MOBILE NUMBER</th>
			<th>EMAIL</th>
			<th>NUMBER OF PROJECTS</th>
			<th>ALL PROJECTS</th>
			<% if is_admin? %>
			<th>USER EMAIL</th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @clients.each_with_index do |client, index|%>
			<tr>
				<td><%= index+1 %></td>
				<td><%= link_to "#{client.name}", client_path(client) %></td>
				<td><%= client.company %></td>
				<td><%= client.mobile_number %></td>
				<td><%= client.email %></td>
				<td><%= client.projects.size%></td>
				<td><%= client.projects.pluck(:name).join(", ") %></td>
				<% if is_admin? %>
				<td><%= client.user.email %></td>
				<% end %>
			</tr>
		<%end%>
	</tbody>
	</table>

taskbox/app/views/clients/new.html.erb
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
			<h1>ADD CLIENT</h1>
		</div>
		<%= render 'form' %>
	</div>
	<div class="col-md-4"></div>
</div>

taskbox/app/views/clients/show.html.erb
<div class="row">
	<div class="col-md-7">
		<div class="page-header">
			<h3>Client Details</h3>
		</div>
		<div class="page-header">
			<h4>NAME</h4> <%= @client.name%> <br/>
			<h4>COMPANY</h4> <%= @client.company%> <br/>
			<h4>EMAIL</h4> <%= @client.email%> <br/>
			<h4>MOBILE</h4> <%= @client.mobile_number%> <br/>
		</div>

		<b><h2>Listing Projects</h2></b>
		<div class="btn-group" role="group" aria-label="...">
			<%= link_to new_project_path(client_id: @client.id), class: "btn btn-primary" do %>
			<span class="glyphicon glyphicon-plus"></span> Add Project<% end %>
			<%= link_to edit_client_path(@client.id), class: "btn btn-warning" do %>
			<span class="glyphicon glyphicon-pencil"></span> Edit Client<% end %>
			<%= link_to client_path(@client.id), data: {method: :delete, confirm: "Do you want to delete?"}, class: "btn btn-danger" do %>
			<span class="glyphicon glyphicon-trash"></span> Delete Client<% end %>
		</div>
		<br/>

		<% if @client.list_projects.empty? %>
			<h3>No Projects found.</h3>
		<% else %>
			<span id="projectCount">
				<h3><%=@client.list_projects.size %> Projects found.</h3>
			</span>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>NAME</th>
						<th>DESCRIPTION</th>
						<th>START DATE</th>
						<th>END DATE</th>
						<th>ESTIMATED BUDGET</th>
						<th>STATUS</th>
					</tr>
				</thead>
				<tbody>
					<% total_budget = 0 %>
					<% @client.list_projects.each do |project| %>
						<% total_budget += project.estimated_budget %>
						<tr id="tr_<%project.id%>">
							<td><%= project.name %></td>
							<td><%= project.description %></td>
							<td><%= project.start_date.strftime("%A, %d %B %Y") %></td>
							<td><%= project.end_date.strftime("%A, %d %B %Y") %></td>
							<td>₹ <%= project.estimated_budget %></td>
							<td><%= project.status %></td>
							<td>
							<div class="btn-group btn-group-sm" role="group" aria-label="...">
							<%= link_to project_path(project), class: "btn btn-info"  do %> 
								<span class="glyphicon glyphicon-eye-open"></span> Show<% end %>
								<%= link_to edit_project_path(project.id), class: "btn btn-warning"  do %> 
								<span class="glyphicon glyphicon-pencil"></span> Edit<% end %>
								<%= link_to projects_path(project.id), data: {method: :delete, confirm: "Do you want to delete?", remote: true}, class: "btn btn-danger"  do %>
								<span class="glyphicon glyphicon-trash"></span> Delete<% end %>
							</div></td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<% tasks = Task.joins(:project).where('projects.client_id = ?', @client.id).size %>

			<h5><b>Total Tasks: <%= tasks %></b></h5>
			<h3>TOTAL BUDGET: ₹ <%= total_budget %></h3>
			<br>
			<hr/>
		<% end %>
		<hr/>
	</div>
	<div class="col-md-5">
		<div class="page-header">
			<h4>Project Timelines</h4>
		</div>
		<% 	timeline_data = []
			for project in @client.list_projects
				project_array = [project.name, project.start_date, project.end_date]
				timeline_data.push(project_array)
			end
		%>

		<%= timeline timeline_data %>
	</div>
</div>