taskbox/config/routes.rb
Rails.application.routes.draw do

  resources :announcements
  
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :catgories

  devise_for :users
  root to: "clients#index"

  resources :clients
  resources :projects
  resources :tasks

  get 'sandbox/clients'
  get 'sandbox/projects'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/products'

  get 'tasker/task'

end

taskbox/app/models/project.rb
class Project < ActiveRecord::Base

	belongs_to :client
	belongs_to :project
	has_many :tasks

	has_many :project_catgories
	has_many :catgories, through: :project_catgories

	before_destroy :destroy_tasks

	validates_presence_of :name, :description, :start_date, :end_date, :estimated_budget, :status
	validates_length_of :description, minimum: 10

	validate :check_date

	def self.new_projects
		Project.where('status = ?', 'New')
	end

	def self.all_projects
		Project.all
	end

	def list_tasks
		Task.where('project_id = ?', self.id)
	end

	def details
		"<h3>NAME</h3> #{self.name} <br/>" + 
		"<h3>CLIENT</h3> <%= link_to #{Client.find(self.client_id).name}, client_path(project.client_id) %> <br/>" + 
		"<h3>DESCRIPTION</h3> #{self.description} <br/>" + 
		"<h3>START DATE</h3> #{self.start_date.strftime("%A, %d %B %Y")} <br/>" +
		"<h3>END DATE</h3>#{self.end_date.strftime("%A, %d %B %Y")}<br/>"
	end

	def destroy_tasks
		self.tasks.each do |task|
			task.destroy
		end
	end

	private 
	def check_date
		if self.end_date <= self.start_date
			errors.add(:end_date, "should be greater than Start Date")
		end
	end
end

taskbox/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_filter :authenticate_user!
	load_and_authorize_resource
	
	def index 
		if params[:status]
			@projects = current_user.projects.where('status = ?',params[:status])
		else
			@projects = Project.all
		end

		if params[:id]
			@projects = current_user.projects.where('client_id = ?',params[:id])
		else
			@projects = current_user.projects
		end
	end

	def new
		@client = Client.find(params[:client_id])
		@project = Project.new
		@project.client_id = @client.id
	end

	def create
		@project = Project.new(project_params)
		@project.user_id = current_user.id
		if @project.save
			redirect_to client_path(@project.client_id)
		else
			render action: "new"
		end
	end

	def show
		begin
			@project = Project.find(params[:id])
			@task = Task.new
			@complete_tasks = Task.list_by_complete.where('project_id = ?', @project.id)
			@incomplete_tasks = Task.list_by_incomplete.where('project_id = ?', @project.id)
			@overdue_tasks = Task.list_by_overdue.where('project_id = ?', @project.id)
		rescue ActiveRecord::RecordNotFound
			redirect_to projects_path, notice: "Project Not Found!"
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		@project.user_id = current_user.id
		if @project.update_attributes(project_params)
			redirect_to client_path(@project.client_id), notice: "Successfully Updated!"
		else
			render action: "edit"
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to client_path(@project.client_id), notice: "Successfully destroyed #{@project.name}'s records."
	end

	private
	def project_params
		#This paramter hash is available in the object params.
		params[:project].permit(:name, :description, :start_date, :status, :end_date, :client_id, :estimated_budget, catgory_ids: [])
	end
end

taskbox/app/helpers/projects_helper.rb
module ProjectsHelper
end

taskbox/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

	<% if @project.errors.any? %>
	<h4>These errors prohibit the form from being saved:</h4>
	<ul style="color: red;">
		<% for msg in @project.errors.full_messages %>
			<li><%= msg%></li>
		<% end %>
	</ul>
	<% end %>
	<!--- collection select takes 4 args: attribute - the foreign key reference client_id, data source - Client.all, primary key, value to be displayed in the drop down -->
	<!--- <label>Client</label><br><%#= f.collection_select parameters, #prompt: Select Client %> -->
	<div class="form-group">
	<label>Client </label><br/>
		<!---<%#= @client.name %>-->
		<%= f.hidden_field :client_id, value: @client.id %>
		<%= f.collection_select :client_id, Client.all, :id, :name, {prompt: "Select Client"}, {class: "form-control", disabled: true, required: true} %><br/>
	</div>

	<div class="form-group">
		<label>Name:</label><br/>
		<%= f.text_field :name, class: "form-control", required: true %><br/>
	</div>

	<div class="form-group">
		<label>Description:</label><br/>
		<%= f.text_area :description, class: "form-control", required: true %><br/>
	</div>

	<div class="form-group">
		<label>Start Date:</label>
		<%= f.date_select :start_date, order: [:month, :day, :year], required: true %><br/>
	</div>

	<div class="form-group">
		<label>End Date:</label>
		<%= f.date_select :end_date, order: [:month, :day, :year], required: true %><br/>
	</div>

	<div class="form-group">
		<label>Status:</label>
		<%= f.select :status, ["New", "Completed", "In Progress"], class: "form-control", required: true %><br/>
	</div>

	<div class="form-group">
		<label>Estimated Budget:</label>
		<%= f.number_field :estimated_budget, minimum: 1, class: "form-control", required: true %><br/>
	</div>

	<div class="form-group">
		<label>Categories:</label><br/>
		<%= f.collection_check_boxes :catgory_ids, current_user.catgories, :id, :name do |b| %>
		<%= b.check_box %> 
		<%= b.label %>
		<br/>
		<% end %>
	</div>

	<%= f.submit "Submit", class: "btn btn-success"%>
<% end %>

taskbox/app/views/projects/destroy.js.erb
$('#projectCount').text('<%= Project.count %>');
$('#tr_<%= @project.id%>').fadeOut();

taskbox/app/views/projects/edit.html.erb
<h1>EDIT PROJECT</h1>

<%= render 'form' %>

taskbox/app/views/projects/index.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="page-header">
			<h1>Listing Projects</h1>
		</div>

		<% if @projects.empty? %>
			<h3>NO PROJECTS FOUND!!</h3>
			<b><%= link_to "List all Projects", projects_path %></b>
		
		<% else %>
			<h3><%= @projects.size%> PROJECTS FOUND</h3>

			<%= link_to projects_path(format: "xls"), class: "btn btn-info btn-sm pull-right" do %>
			<span class="glyphicon glyphicon-download-alt"></span>Export to Excel
			<% end %>
		
			<hr/> 	

			<b><h4> Filter by Status : </h4><br/> 
			<div class="btn-group" role="group" aria-label="...">	
				<%= link_to "New", projects_path(status: "New"), class: "btn btn-primary"%>
				<%= link_to "Completed", projects_path(status: "Completed"), class: "btn btn-primary" %>
				<%= link_to "In Progress", projects_path(status: "In Progress"), class: "btn btn-primary" %>
			</div>
			</b>
			<br/>
			
			<hr/>

			<b><h4> Filter by Client : </h4><br/> 
			<div class="btn-group" role="group" aria-label="...">
			<% index = 0 %>
			<% for client in current_user.clients %>
				<% index += 1 %>
				<%= link_to client.name, projects_path(id: client.id), class: "btn btn-primary" %>
				<% if index%5 == 0 %>
					<br/><br/>
				<% end %>
			<% end %>
			</div>
			</b>
		
			<b><%= link_to "List all Projects", projects_path, class: "btn btn-primary" %></b>
			<br/>
			<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>NAME</th>
					<th>CLIENT</th>
					<th>DESCRIPTION</th>
					<th>START DATE</th>
					<th>END DATE</th>
					<th>STATUS</th>
				</tr>
			</thead>
			<tbody>
				<% @projects.each_with_index do |project, index|%>
					<tr>
						<td><%=index+1 %></td>
						<td><%=project.name %></td>
						<td><%=link_to project.client.try(:name), client_path(project.client_id) %></td>
						<td><%=project.description %></td>
						<td><%=project.start_date.strftime("%A, %d %B %Y") %></td>
						<td><%=project.end_date.strftime("%A, %d %B %Y") %></td>
						<td><%=project.status%></td>
						<td>
						<div class="btn-group btn-group-sm" role="group" aria-label="...">
						<%= link_to project_path(project), class: "btn btn-info" do %> 
							<span class="glyphicon glyphicon-eye-open"></span> Show <% end %>
							<%= link_to edit_project_path(project.id), class: "btn btn-warning" do %> 
							<span class="glyphicon glyphicon-pencil"></span> Edit <% end %>
							<%= link_to project_path(project.id), data: {method: :delete, confirm: "Do you want to delete?"}, class: "btn btn-danger" do %>
							<span class="glyphicon glyphicon-trash"></span> Destroy <% end %>
						</div></td>
					</tr>
					<%end%>
			</tbody>
			</table>
		<% end %>
	</div>
	<div class="col-md-3">
		<div class="page-header">
			<h1>Clients' Statistics</h1>
			<% 	data = {}
				data["New Projects"] = @projects.where('status = ?', "New").size
				data["In Progress"] = @projects.where('status = ?', "In Progress").size
				data["Completed"] = @projects.where('status = ?', "Completed").size 
			%>

			<%= pie_chart(data) %>
			<%= bar_chart(data) %>
		</div>
	</div>
</div>

taskbox/app/views/projects/index.xls.erb
	<table border="2">
	<thead>
		<tr>
			<th>#</th>
			<th>NAME</th>
			<th>CLIENT</th>
			<th>DESCRIPTION</th>
			<th>START DATE</th>
			<th>END DATE</th>
			<th>TASKS</th>
		</tr>
	</thead>
	<tbody>
		<% @projects.each_with_index do |project, index|%>
			<tr>
				<td><%=index+1 %></td>
				<td><%=project.name %></td>
				<td><%=link_to project.client.try(:name), client_path(project.client_id) %></td>
				<td><%=project.description %></td>
				<td><%=project.start_date.strftime("%A, %d %B %Y") %></td>
				<td><%=project.end_date.strftime("%A, %d %B %Y") %></td>
				<td><%= project.tasks.pluck(:title).join(", ") %></td>
			</tr>
			<%end%>
	</tbody>
	</table>

taskbox/app/views/projects/new.html.erb
<h1>NEW PROJECT</h1>

<%=render 'form' %>

taskbox/app/views/projects/show.html.erb
<div class="row">
	<div class="col-md-8">
		<div class="page-header">
			<b><h2><%= @project.name%></h2></b>
			<%=link_to "#{Client.find(@project.client_id).name}", client_path(@project.	client_id) %> <br/> 
			<%= @project.description %><br/>
			<%= @project.start_date.strftime("%A, %d %B %Y")%> to
			<%= @project.end_date.strftime("%A, %d %B %Y")%><br/>
			<%= @project.catgories.pluck(:name).join(", ") %><br/><br/>
			
			<%= link_to project_path(@project.id, format: "xls"), class: "btn btn-info btn-sm pull-right" do %>
			<span class="glyphicon glyphicon-download-alt"></span>Export to Excel
			<% end %>
		</div>

		<div class="page-header">
			<h1>Listing Tasks</h1>
		</div>

		<% if @project.list_tasks.size > 0 %>

			<p>Project Status:</p><br/>
			<div class="progress">
				<% task_completion = (@complete_tasks.size.to_f / @project.list_tasks.size.to_f)*100.0%>
  				<div class="progress-bar progress_success progress-bar-stripped" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: <%= task_completion.to_i %>%;"><%= task_completion.to_i %>%</div>
			</div>
		<% end %>

		<%= link_to edit_project_path(@project.id), class: "btn btn-warning" do %>
		<span class="glyphicon glyphicon-pencil"></span> Edit this Project<% end %>

		<%= link_to edit_project_path(@project.id), class: "btn btn-danger" do %>
		<span class="glyphicon glyphicon-trash"></span> Delete this Project<% end %>

		<% if @project.list_tasks.empty? %>
			<h2>No Tasks found.</h2>
		<% else %>
			<h2><%=@project.list_tasks.size %> Tasks found.</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>TITLE</th>
					<th>DUE DATE</th>
					<th>IS COMPLETED</th>
				</tr>
			</thead>
			<tbody>
				<% @project.list_tasks.each_with_index do |task, index|%>
				<% if task.is_completed %>
				<tr>
					<td><s><%=index+1 %></s></td>
					<td><s><%=task.title %></s></td>
					<td><s><%=task.due_date.strftime("%A, %d %B %Y") %></s></td>
					<td><s>Yes</s></td>
					<td>
						<%= link_to task_path(task), class: "btn btn-info" do %>
						<span class="glyphicon glyphicon-eye-open"></span> Show<% end %>
						<%= link_to tasks_mark_as_incomplete_path(task_id: task.id), class: "btn btn-warning" do %>
						<span class="glyphicon glyphicon-remove"></span> Mark as Incomplete!<% end %>
						</td>
				</tr>
				<% else %>
				<tr>
					<td><%=index+1 %></td>
					<td><%=task.title %></td>
					<td><%=task.due_date.strftime("%A, %d %B %Y") %></td>
					<td>No</td>
					<td>
						<%= link_to task_path(task), class: "btn btn-info" do %>
						<span class="glyphicon glyphicon-eye-open"></span> Show<% end %>
						<%= link_to tasks_mark_as_complete_path(task_id: task.id), class: "btn btn-success" do %>
						<span class="glyphicon glyphicon-ok"></span> Mark as Complete!<% end %>
					</td>
				</tr>
				<% end %>
			<%end%>
			</tbody>
		</table>
		<hr/>

		<% if @complete_tasks.size > 0 %>
			<h4>Completed Tasks:</h4>
			<ol>
				<% @complete_tasks.each do |task| %>
				<li><%= task.title %></li>
				<% end %>
			</ol>

		<hr/>
		<% end %>

		<% if @incomplete_tasks.size > 0 %>
			<h4>Incomplete Tasks:</h4>
			<ol>
				<% @incomplete_tasks.each do |task| %>
				<li><%= task.title %></li>
				<% end %>
			</ol>
		<hr/>
		<% end %>

		<% if @overdue_tasks.size > 0 %>
			<h4>Overdue Tasks:</h4>
			<ol>
				<% @overdue_tasks.each do |task| %>
				<li><%= task.title %></li>
				<% end %>
			</ol>
		<hr/>
		<% end %>
	<% end %>

	<!-- Button trigger modal -->
	<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
	  Add Task
	</button>
	
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
	      </div>
	      <div class="modal-body">
	      	<h3>Add Task</h3>
			<%= form_for @task do |f| %>
			
			<%= f.hidden_field :project_id, value: @project.id %>
			
			<div class="form-group">
				<label>Title</label><br/>
				<%= f.text_field :title %>
			</div>
			
			<div class="form-group">
				<label>Due Date</label><br/>
				<%= f.date_select :due_date, order:[:month, :day, :year] %>
			</div>
			
			<div class="form-group">
				<label>Is Completed? </label>
				<%= f.check_box :is_completed %>
			</div>
			
			<%= f.submit "Submit", class: "btn btn-primary" %>
			
			<% end %>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary">Save changes</button>
	      </div>
	    </div>
	  </div>
	</div>
	<br/>
	<br/>

	</div>

	<div class="col-md-4">
		<div class="page-header">
			<h1>Project' Statistics</h1>
			<% 	data = {}
				data["Complete Tasks"] = @complete_tasks.size
				data["Incomplete Tasks"] = @incomplete_tasks.size
				data["Overdue Tasks"] = @overdue_tasks.size
				%>
			<%= pie_chart(data) %>
			<%= bar_chart(data) %>
		</div>
	</div>
</div>

taskbox/app/views/projects/show.xls.erb
<p>NAME - <%= @project.name%> </p>
<p>CLIENT - <%=link_to "#{Client.find(@project.client_id).name}", client_path(@project.client_id) %> </p> 
<p>DESCRIPTION - <%= @project.description %><br/>
<p>START DATE - <%= @project.start_date.strftime("%A, %d %B %Y")%></p>
<p>END DATE - <%= @project.end_date.strftime("%A, %d %B %Y")%></p>
<p>CATEGORIES - <%= @project.catgories.pluck(:name).join(", ") %>

<table border="2">
	<thead>
		<tr>
			<th>#</th>
			<th>TITLE</th>
			<th>DUE DATE</th>
			<th>IS COMPLETED</th>
		</tr>
	</thead>
	<tbody>
		<% @project.list_tasks.each_with_index do |task, index|%>
		<% if task.is_completed %>
			<tr>
				<td><s><%=index+1 %></s></td>
				<td><s><%=task.title %></s></td>
				<td><s><%=task.due_date.strftime("%A, %d %B %Y") %></s></td>
				<td><s><%=task.is_completed %></s></td>
			</tr>
		<% else %>
		<tr>
				<td><%=index+1 %></td>
				<td><%=task.title %></td>
				<td><%=task.due_date.strftime("%A, %d %B %Y") %></td>
				<% if task.is_completed %>
					<td>Yes</td>
				<% else %>
					<td>No</td>
				<% end %>
			</tr>
			<% end %>
		<%end%>
	</tbody>
	</table>