taskbox/config/routes.rb
Rails.application.routes.draw do

  resources :announcements
  
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :catgories

  devise_for :users
  root to: "clients#index"

  resources :clients
  resources :projects
  resources :tasks

  get 'sandbox/clients'
  get 'sandbox/projects'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/products'

  get 'tasker/task'

end

taskbox/app/models/catgory.rb
class Catgory < ActiveRecord::Base
	belongs_to :user

	has_many :project_catgories
	has_many :projects, through: :project_catgories

	validates_presence_of :name
end

taskbox/app/controllers/catgories_controller.rb
class CatgoriesController < ApplicationController
  before_action :set_catgory, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /catgories
  # GET /catgories.json
  def index
    @catgories = current_user.catgories
  end

  # GET /catgories/1
  # GET /catgories/1.json
  def show
  end

  # GET /catgories/new
  def new
    @catgory = Catgory.new
  end

  # GET /catgories/1/edit
  def edit
  end

  # POST /catgories
  # POST /catgories.json
  def create
    @catgory = Catgory.new(catgory_params)
    @catgory.user_id = current_user.id

    respond_to do |format|
      if @catgory.save
        format.html { redirect_to @catgory, notice: 'Catgory was successfully created.' }
        format.json { render :show, status: :created, location: @catgory }
      else
        format.html { render :new }
        format.json { render json: @catgory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catgories/1
  # PATCH/PUT /catgories/1.json
  def update
    respond_to do |format|
      if @catgory.update(catgory_params)
        format.html { redirect_to @catgory, notice: 'Catgory was successfully updated.' }
        format.json { render :show, status: :ok, location: @catgory }
      else
        format.html { render :edit }
        format.json { render json: @catgory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catgories/1
  # DELETE /catgories/1.json
  def destroy
    @catgory.destroy
    respond_to do |format|
      format.html { redirect_to catgories_url, notice: 'Catgory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catgory
      @catgory = Catgory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catgory_params
      params.require(:catgory).permit(:name, :user_id)
    end
end

taskbox/app/helpers/catgories_helper.rb
module CatgoriesHelper
end

taskbox/app/views/catgories/_form.html.erb
<%= form_for(@catgory) do |f| %>
  <% if @catgory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catgory.errors.count, "error") %> prohibited this catgory from being saved:</h2>

      <ul>
      <% @catgory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

taskbox/app/views/catgories/edit.html.erb
<h1>Editing catgory</h1>

<%= render 'form' %>

<%= link_to 'Show', @catgory %> |
<%= link_to 'Back', catgories_path %>

taskbox/app/views/catgories/index.html.erb
<h1>Listing catgories</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @catgories.each do |catgory| %>
      <tr>
        <td><%= catgory.name %></td>
        <td><%= link_to catgory, class: "btn btn-info btn-sm" do %><span class="glyphicon glyphicon-eye-open"></span>Show<% end %></td>
        <td><%= link_to edit_catgory_path(catgory), class: "btn btn-warning btn-sm" do %><span class="glyphicon glyphicon-pencil"></span>Edit<% end %></td>
        <td><%= link_to catgory, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" do %><span class="glyphicon glyphicon-trash"></span>Delete<% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Catgory', new_catgory_path, class: "btn btn-info" %>

taskbox/app/views/catgories/new.html.erb
<h1>New catgory</h1>

<%= render 'form' %>

<%= link_to 'Back', catgories_path %>

taskbox/app/views/catgories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @catgory.name %>
</p>

<%= link_to 'Edit', edit_catgory_path(@catgory) %> |
<%= link_to 'Back', catgories_path %>